### ISSUE TITLE
Certificados

### ISSUE THREAD

**Issue by quindai** [nodeschool/luanda#3]
:cat:Nodeschoolers:cat:

Votem aí, Sim ou Não?

**Comment by AdilsonDala** [comment]
Sim

**Comment by Ynes-Luys** [comment]
Sim

**Comment by paulotmarques** [comment]
/* ##  SIM  ## */

**Comment by bmpereira** [comment]
Claro que SIM!

**Comment by thisis2m** [comment]
Sim.

**Comment by Nanitamo** [comment]
Sim

**Comment by curado** [comment]
Sim

**Comment by nerivaldo** [comment]
Sim

**Comment by nerivaldo** [comment]
Sim

**Comment by Miguel4039** [comment]
Sim

**Comment by firminochangani** [comment]
Sim

**Comment by doriel** [comment]
Sim

**Comment by quindai** [comment]
Pessoal, acredito que emitiremos certificados digitais, devido aos custos adicionais e também salve o planeta.
 ![Salve o planeta, imprima menos](https://image.freepik.com/free-vector/save-the-planet_23-2147507691.jpg)

**Comment by Linkdu** [comment]
Sim , Certificados Digitais...
